# Generated by Django 6.0.1 on 2026-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_member_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(null=True),
        ),
    ]
